"""Static integrity checks for the investment prototype UI.

The repository does not include a frontend test runner. These focused checks
guard the product-boundary rules that can be verified from the plain
JavaScript source without introducing new tooling.
"""

from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[4]
APP_JS = REPO_ROOT / "applications" / "investment" / "prototype-ui" / "app.js"
FIXTURES_JS = REPO_ROOT / "applications" / "investment" / "prototype-ui" / "fixtures.js"
README = REPO_ROOT / "applications" / "investment" / "prototype-ui" / "README.md"


def read_app() -> str:
    """Return the prototype UI source."""
    return APP_JS.read_text(encoding="utf-8")


def read_prototype_text() -> str:
    """Return UI source, fixture, and README text for boundary checks."""
    return "\n".join(
        path.read_text(encoding="utf-8") for path in (APP_JS, FIXTURES_JS, README)
    )


def test_user_cases_cannot_attach_northstar_fixture_analysis() -> None:
    """User-created cases must not be able to inherit Northstar analysis."""
    source = read_prototype_text()

    assert "Use Completed Mock Analysis" not in source
    assert "attachCompletedFixture" not in source
    assert "Attach the completed fixture analysis" not in source
    assert "attaches static fixture analysis to the selected UI case" not in source


def test_created_cases_initialize_empty_reasoning_layers() -> None:
    """Draft cases should start with empty case-owned reasoning data."""
    source = read_prototype_text()

    for expected in (
        "evidence: []",
        "rikPositions: []",
        "contestedPropositions: []",
        "decisionLedger: []",
        "investmentConditions: []",
        "unresolvedQuestions: []",
        "decision: null",
    ):
        assert expected in source

    assert "No structured evidence has been attached to this case." in source


def test_evidence_source_is_not_silently_copied_from_case_material() -> None:
    """The optional evidence source field should start empty."""
    source = read_app()

    assert '"Evidence Source Text (optional)"' in source
    assert '"source_text",\n      "",' in source


def test_execution_result_has_dedicated_provenance_boundary() -> None:
    """Risk RIK output should render under an explicit execution boundary."""
    source = read_prototype_text()

    assert "Prototype Execution Result" in source
    assert "Deterministic Development Execution" in source
    assert "It is not live model reasoning." in source


def test_fixture_analysis_has_explicit_demonstration_boundary() -> None:
    """The Northstar reasoning graph should be labelled as fixture data."""
    source = read_prototype_text()

    assert "Fixture Institutional Analysis" in source
    assert (
        "This analysis was not generated by the current executable Risk RIK pipeline."
        in source
    )
